title: Andr√© Rodrigues
show_downloads: "false"
description: PhD Student at LASIGE, Universidade de Lisboa
github:
  aboutme: aboutme.html
  publications: publications.html
theme: jekyll-theme-architect
